import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import type { SendMessageInput } from "../../kleinanzeigen/index.js";
import { getConversation, getConversations, sendMessage } from "../../kleinanzeigen/index.js";
import { InvalidInputError } from "../../utils/errors.js";
import { handleTool } from "../format.js";

interface GetConversationsArgs {
  limit?: number;
}

interface GetConversationArgs {
  conversationId: string;
}

const getConversationsSchema = {
  limit: z.number().int().positive().max(200).optional().describe("Max conversations to return."),
};

const getConversationSchema = {
  conversationId: z.string().min(1).describe("Conversation id from get_conversations."),
};

const sendMessageSchema = {
  listingId: z.string().optional().describe("Listing id to contact (for a new conversation)."),
  conversationId: z.string().optional().describe("Existing conversation id to reply in."),
  message: z.string().min(1).describe("Exact message text to send. Never generated by the MCP."),
};

export function registerMessageTools(server: McpServer): void {
  server.registerTool(
    "get_conversations",
    {
      title: "Get conversations",
      description: "List the inbox conversations of the logged-in user. Read-only.",
      inputSchema: getConversationsSchema,
      annotations: { readOnlyHint: true, openWorldHint: true },
    },
    handleTool<GetConversationsArgs>("get_conversations", async (args) => ({
      conversations: await getConversations(args.limit ?? 50),
    })),
  );

  server.registerTool(
    "get_conversation",
    {
      title: "Get conversation",
      description: "Read the full message history of one conversation. Read-only.",
      inputSchema: getConversationSchema,
      annotations: { readOnlyHint: true, openWorldHint: true },
    },
    handleTool<GetConversationArgs>("get_conversation", async (args) =>
      getConversation(args.conversationId),
    ),
  );

  server.registerTool(
    "send_message",
    {
      title: "Send message",
      description:
        "MUTATING ACTION: sends a real message from the user's Kleinanzeigen account. " +
        "Provide either `conversationId` (reply) or `listingId` (new contact). " +
        "The message text is sent exactly as given; the server never writes it. " +
        "Clients should require explicit user approval before calling this tool.",
      inputSchema: sendMessageSchema,
      annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
    },
    handleTool<SendMessageInput>("send_message", async (args) => {
      if (!args.conversationId && !args.listingId && !args.listingUrl) {
        throw new InvalidInputError("Either `conversationId` or `listingId` must be provided.");
      }
      if (args.conversationId && (args.listingId || args.listingUrl)) {
        throw new InvalidInputError("Provide either `conversationId` or `listingId`, not both.");
      }
      return sendMessage({
        listingId: args.listingId,
        conversationId: args.conversationId,
        message: args.message,
      });
    }),
  );
}
